---
driver:
  name: vagrant

provisioner:
  name: chef_solo
  always_update_cookbooks: true
  product_version: '14.3'

verifier:
  name: inspec

platforms:
  - name: debian-9

suites:
  - name: default
    run_list:
      - recipe[torrentbox::default]
    verifier:
      inspec_tests:
        - test/integration/default
    attributes:
