---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  always_update_cookbooks: true
  product_name: chef
  product_version: '14.2'

verifier:
  name: inspec

platforms:
  - name: debian-9
    architecture: x86_64

suites:
  - name: default
    run_list:
      - recipe[torrentbox::default]
    verifier:
      inspec_tests:
        - test/integration/default
    lifecycle:
      post_converge:
        - local: sleep 20
    attributes:
      torrentbox: &torrentbox_attributes
        iptables:
          destination_whitelist:
            - 169.254.169.123
            - 169.254.168.0/24
        openvpn:
          username: <%= ENV['OPENVPN_USERNAME'] %>
          password: <%= ENV['OPENVPN_PASSWORD'] %>
        remote_access:
          ssh_authorized_keys:
            - <%= ENV['KITCHEN_SSH_PUBLIC_KEY'] %>
        fileshares:
          - name: Share One
            path: /tmp/shareone
          - name: Share Two
            path: /tmp/share two
  - name: novpn
    run_list:
      - recipe[torrentbox::default]
    verifier:
      inspec_tests:
        - test/integration/novpn
    lifecycle:
      post_converge:
        - local: sleep 20
    attributes:
      torrentbox:
        <<: *torrentbox_attributes
        vpn_enabled: false
