---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  always_update_cookbooks: true
  product_name: chef
  product_version: '14.2'

verifier:
  name: inspec

platforms:
  - name: debian-9

suites:
  - name: default
    run_list:
      - recipe[torrentbox::default]
    verifier:
      inspec_tests:
        - test/integration/default
    attributes:
      torrentbox: &torrentbox_attributes
        iptables:
          destination_whitelist:
            - 169.254.169.123
            - 169.254.168.0/24
        openvpn:
          username: <%= ENV['OPENVPN_USERNAME'] %>
          password: <%= ENV['OPENVPN_PASSWORD'] %>
  - name: novpn
    run_list:
      - recipe[torrentbox::default]
    verifier:
      inspec_tests:
        - test/integration/novpn
    attributes:
      torrentbox:
        <<: *torrentbox_attributes
        vpn_enabled: false
