---
version: 2
jobs:
  test:
    docker:
      - image: chef/chefdk:3.1
    environment:
      KITCHEN_LOCAL_YAML: .kitchen.ec2.yml
    steps:
      - checkout
      - run: chef exec rake
workflows:
  version: 2
  test:
    jobs:
      - test
