---
version: 2
jobs:
  test:
    docker:
      - image: chef/chefdk:4.7.1
    environment:
      KITCHEN_LOCAL_YAML: .kitchen.ec2.yml
      CHEF_LICENSE: accept
    steps:
      - checkout
      - run:
          name: Style Checking
          command: chef exec rake style
      - run:
          name: Unit Tests
          command: chef exec rake unit
      - run:
          name: Integration Tests
          command: chef exec rake integration
      - run:
          name: Clean-up
          command: chef exec kitchen destroy
          when: always

workflows:
  version: 2
  test:
    jobs:
      - test
